cuoiki/bailam/Blog_5-18-11-2014/Models/Post.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Blog_5_18_11_2014.Models
{
    public class Post
    {
        public int ID { set; get; }
        [Required(ErrorMessage = "không được bỏ trống")]
        public String Title { set; get; }
        [Required(ErrorMessage = "không được bỏ trống")]
        public String Body { set; get; }
        public DateTime DateCreated { set; get; }

        public virtual UserProfile UserProFile { set; get; }
        public int UserProfileUserId { set; get; }

        public virtual ICollection<Comment> Comments { set; get; }
        public virtual ICollection<Tag> Tags { set; get; }
    }
}

cuoiki/bailam/Blog_5-18-11-2014/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_5_18_11_2014.Models;

namespace Blog_5_18_11_2014.Controllers
{
    public class CommentController : Controller
    {
        private BlogDBContext db = new BlogDBContext();

        //
        // GET: /Comment/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var comments = db.Comments.Include(c => c.Post);
            return View(comments.ToList());
        }

        //
        // GET: /Comment/Details/5

        public ActionResult Details(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // GET: /Comment/Create
        [Authorize]
        public ActionResult Create()
        {
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title");
            return View();
        }

        //
        // POST: /Comment/Create
        [Authorize]
        [HttpPost]
        public ActionResult Create(Comment comment, int idpost)
        {
            if (ModelState.IsValid)
            {
                comment.PostID = idpost;
                comment.DataCreated = DateTime.Now;
                db.Comments.Add(comment);
                db.SaveChanges();
                return PartialView("viewComment",comment);
                //return RedirectToAction("Details/" + idpost, "Post");
            }

            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Edit/5
        [Authorize(Users = "admin")]
        public ActionResult Edit(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // POST: /Comment/Edit/5
        [Authorize(Users = "admin")]
        [HttpPost]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                db.Entry(comment).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.PostID = new SelectList(db.Posts, "ID", "Title", comment.PostID);
            return View(comment);
        }

        //
        // GET: /Comment/Delete/5
        [Authorize(Users = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Comment comment = db.Comments.Find(id);
            if (comment == null)
            {
                return HttpNotFound();
            }
            return View(comment);
        }

        //
        // POST: /Comment/Delete/5
        [Authorize(Users = "admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Comment comment = db.Comments.Find(id);
            db.Comments.Remove(comment);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

cuoiki/bailam/Blog_5-18-11-2014/Controllers/PostController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_5_18_11_2014.Models;

namespace Blog_5_18_11_2014.Controllers
{
    [Authorize(Users = "admin")]
    public class PostController : Controller
    {
        private BlogDBContext db = new BlogDBContext();

        //
        // GET: /Post/
        [AllowAnonymous]
        public ActionResult Index()
        {
            var posts = db.Posts.Include(p => p.UserProFile);
            return View(posts.ToList());
        }

        //
        // GET: /Post/Details/5
        [AllowAnonymous]
        public ActionResult Details(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewData["idpost"] = id;
            return View(post);
        }

        //
        // GET: /Post/Create
        [Authorize(Users = "admin")]
        public ActionResult Create()
        {
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName");
            return View();
        }

        //
        // POST: /Post/Create
        [Authorize(Users = "admin")]
        [HttpPost]
        public ActionResult Create(Post post,string content)
        {
            if (ModelState.IsValid)
            {
                int userID = db.UserProfiles.Select(x => new { x.UserId, x.UserName })
                    .Where(y => y.UserName == User.Identity.Name).Single().UserId;

                post.DateCreated = DateTime.Now;
                // Tao list cac Tag
                List<Tag> Tags = new List<Tag>();
                // Tach cac tag theo dau ,
                string[] TagContent = content.Split(',');
                // Lap cac tag vua tach
                foreach (string item in TagContent)
                {
                    //Tim xem Tag Content da co hay chua
                    Tag TagExits = null;
                    var ListTag = db.Tags.Where(y => y.content.Equals(item));
                    if (ListTag.Count() > 0)
                    {
                        // neu co tag roi thi them post vao 
                        TagExits = ListTag.First();
                        TagExits.Posts.Add(post);
                    }
                    else
                    {
                        // neu chua co tag thi tao moi
                        TagExits = new Tag();
                        TagExits.content = item;
                        TagExits.Posts = new List<Post>();
                        TagExits.Posts.Add(post);
                    }
                    //add vao List cac Tag
                    Tags.Add(TagExits);
                }
                //Gan list Tag cho Post
                post.Tags = Tags;
                post.UserProfileUserId = userID;
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Edit/5
        [Authorize(Users = "admin")]
        public ActionResult Edit(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // POST: /Post/Edit/5
        [Authorize(Users = "admin")]
        [HttpPost]
        public ActionResult Edit(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UserProfileUserId = new SelectList(db.UserProfiles, "UserId", "UserName", post.UserProfileUserId);
            return View(post);
        }

        //
        // GET: /Post/Delete/5
        [Authorize(Users = "admin")]
        public ActionResult Delete(int id = 0)
        {
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        //
        // POST: /Post/Delete/5
        [Authorize(Users = "admin")]
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

cuoiki/bailam/Blog_5-18-11-2014/Controllers/TagController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Blog_5_18_11_2014.Models;

namespace Blog_5_18_11_2014.Controllers
{
    public class TagController : Controller
    {
        private BlogDBContext db = new BlogDBContext();

        //
        // GET: /Tag/

        public ActionResult Index()
        {
            
            return View(db.Tags.ToList());
        }

        //
        // GET: /Tag/Details/5

        public ActionResult Details(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // GET: /Tag/Create

        public ActionResult Create()
        {
            return View();
        }

        //
        // POST: /Tag/Create

        [HttpPost]
        public ActionResult Create(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Tags.Add(tag);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(tag);
        }

        //
        // GET: /Tag/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Edit/5

        [HttpPost]
        public ActionResult Edit(Tag tag)
        {
            if (ModelState.IsValid)
            {
                db.Entry(tag).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(tag);
        }

        //
        // GET: /Tag/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Tag tag = db.Tags.Find(id);
            if (tag == null)
            {
                return HttpNotFound();
            }
            return View(tag);
        }

        //
        // POST: /Tag/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            Tag tag = db.Tags.Find(id);
            db.Tags.Remove(tag);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

cuoiki/bailam/Blog_5-18-11-2014/Views/Post/Create.cshtml
@model Blog_5_18_11_2014.Models.Post

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
            
        </div>

       

   


        <div class="editor-label">
            <h2>Tag:</h2>
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => new Blog_5_18_11_2014.Models.Tag().content)
            @Html.ValidationMessageFor(model => new Blog_5_18_11_2014.Models.Tag().content)
        </div>  


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cuoiki/bailam/Blog_5-18-11-2014/Views/Post/Delete.cshtml
@model Blog_5_18_11_2014.Models.Post

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Post</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.Body)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Body)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.DateCreated)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.UserProFile.UserName)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.UserProFile.UserName)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

cuoiki/bailam/Blog_5-18-11-2014/Views/Post/Details.cshtml
@model Blog_5_18_11_2014.Models.Post

@{
    ViewBag.Title = "Details";
}


<fieldset>
    <legend>Post</legend>

  
    <div class="display-field">
        <h2><div style="color: #00ff21;">@Html.DisplayFor(model => model.Title)</div></h2>
    </div>
    
   
    <div class="display-field">
        @if(Model.ID==1){<div align="center"><img border ="0" src="/images/vinhhalong.jpg"
    alt="bia" width="450" height="200"></div>}
         @if(Model.ID==21){<div align="center"><img border ="0" src="/images/nhatrang.jpg"
    alt="bia" width="450" height="200"></div>}
        @if(Model.ID==22){<div align="center"><img border ="0" src="/images/phongnha.jpg"
    alt="bia" width="450" height="200"></div>}
        @if(Model.ID==23){<div align="center"><img border ="0" src="/images/chua1cot.jpg"
    alt="bia" width="450" height="200"></div>}
         @if(Model.ID==24){<div align="center"><img border ="0" src="/images/codohue.jpg"
    alt="bia" width="450" height="200"></div>}
         <span style="font-family: Arial; font-size: 15pt;">@Html.DisplayFor(model => model.Body)</span>
        
         
    </div>

  
  <div class="display-field">
      <div align="right">
        <h6>@Html.DisplayFor(model => model.DateCreated)</h6>
    </div></div>
</fieldset>


   

<fieldset> 
    <div align="right">
       <legend>Tags </legend>
        Tags:
          @foreach (var Tag in Model.Tags.Take(10))
          {
             string nameTag = Tag.content;

                <td>
                 @Html.ActionLink(nameTag, "Details/"+Tag.TagID,"Tag")
                </td>
          }
    </div>
</fieldset>
<div align="right">
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p></div>


<legend><h6>Để bình luận của bạn tại đây</h6></legend>
@Html.Partial("_addComment", new Blog_5_18_11_2014.Models.Comment(), ViewData)


<fieldset>
    <legend>List(Comments)</legend>
    <div id ="result">
    @foreach (var comment in Model.Comments.OrderByDescending(x => x.DataCreated).Take(5)) 
    {  
         <span style="font-family: Arial; font-size: 15pt;">
        <div class="display-field">
            <h6>@Html.DisplayFor(x => comment.Body)</h6>
        </div>
             </span>
      
        <span style="font-family: Arial; font-size: 13pt;"> 
      <div class="display-field">
           cách đây @Html.DisplayFor(x => comment.LastTime) phút
        </div> </span>
               
    }
        </div>
    </fieldset>

cuoiki/bailam/Blog_5-18-11-2014/Views/Post/Edit.cshtml
@model Blog_5_18_11_2014.Models.Post

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Post</legend>

        @Html.HiddenFor(model => model.ID)

        <div class="editor-label">
            @Html.LabelFor(model => model.Title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Title)
            @Html.ValidationMessageFor(model => model.Title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Body)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.DateCreated)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.DateCreated)
            @Html.ValidationMessageFor(model => model.DateCreated)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.UserProfileUserId, "UserProFile")
        </div>
        <div class="editor-field">
            @Html.DropDownList("UserProfileUserId", String.Empty)
            @Html.ValidationMessageFor(model => model.UserProfileUserId)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

cuoiki/bailam/Blog_5-18-11-2014/Views/Post/Index.cshtml
@model IEnumerable<Blog_5_18_11_2014.Models.Post>

@{
    ViewBag.Title = "Index";
}

<h1><div style="color: #ffd800;">Danh Lam Thắng Cảnh</div></h1>
<p>
        @Html.ActionLink("Create New", "Create")
 </p>

<section class="featured"> 
@foreach (var item in Model) {
    <tr>
       
            <h2><div style="color: #00ff21;">@Html.DisplayFor(modelItem => item.Title)</div></h2>

       @if(item.ID==1){ <a href="http://localhost:1170/Post/Details/1" class="thumb">
               <div align="center"><img border ="0" src="/images/vinhhalong.jpg"
    alt="bia" width="450" height="200"></div></a>
          <span style="font-family: Arial; font-size: 15pt;">Vị trí: Vịnh Hạ Long nằm ở vùng Đông Bắc Việt Nam,
                là một phần phía tây Vịnh Bắc Bộ, bao gồm vùng biển của thành phố Hạ Long,
                thị xã Cẩm Phả và một phần của huyện đảo Vân Đồn. Phía tây nam giáp đảo Cát Bà, 
               phía tây giáp đất liền với đường bờ biển dài 120 km.... </span>
       
           }
        @if (item.ID == 21)
        { <a href="http://localhost:1170/Post/Details/21" class="thumb">
            <div align="center"><img border="0" src ="/images/nhatrang.jpg"
            alt="nt" width="450" height="200" />
                              </div></a>
            <span style ="font-family:Arial;font-size:15pt;">Nha Trang là một thành phố ven biển và là trung tâm chính trị, kinh tế, văn hóa, 
                khoa học kỹ thuật và du lịch của tỉnh Khánh Hòa, Việt Nam. Thiên nhiên đã ưu ái ban tặng cho thành phố biển Nha Trang 
                tất cả những gì mà một vùng duyên hải Nam Trung bộ...
                </span>
        }
         @if (item.ID == 22)
         { <a href="http://localhost:1170/Post/Details/22" class="thumb">
            <div align="center"><img border="0" src ="/images/phongnha.jpg"
            alt="nt" width="450" height="200" />
                              </div></a>
            <span style ="font-family:Arial;font-size:15pt;">Phong Nha - Kẻ Bàng là khu bảo tồn thiên nhiên đã được UNESCO chính thức công nhận.
                 Đây là nơi có hang Sơn Động – hang đá lớn nhất thế giới và khoảng 300 hang động khác...
                </span>
        }
         @if (item.ID == 23)
         { <a href="http://localhost:1170/Post/Details/23" class="thumb">
            <div align="center"><img border="0" src ="/images/chua1cot.jpg"
            alt="nt" width="450" height="200" />
                              </div></a>
            <span style ="font-family:Arial;font-size:15pt;">Nằm giữa trung tâm thủ đô Hà Nội, chùa Một Cột được xây dựng từ năm 1049 với mục đích
                 tái hiện lại một giấc mơ của vua Lý Thái Tông...
                </span>
        }
         @if(item.ID==24){ <a href="http://localhost:1170/Post/Details/24" class="thumb">
               <div align="center"><img border ="0" src="/images/codohue.jpg"
    alt="bia" width="450" height="200"></div></a>
          <span style="font-family: Arial; font-size: 15pt;">Từng là trung tâm của triều đại nhà Nguyễn, cố đô Huế là tập hợp của một loạt các 
              ngôi chùa, cổng chào, dòng suối, phòng ốc, vườn thượng uyển và cả những ngôi chùa cổ kính.... </span>
       
           }
       
          <div align="right"><h6> @Html.DisplayFor(modelItem => item.DateCreated  )
        
       
           @Html.DisplayFor(modelItem => item.UserProFile.UserName)</h6>
        
        
            @Html.ActionLink("Edit", "Edit", new { id=item.ID }) |
            @Html.ActionLink("Details", "Details", new { id=item.ID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.ID })</div>
        
    </tr>
}
      
 </section>

cuoiki/bailam/Blog_5-18-11-2014/Views/Post/_addComment.cshtml
@model Blog_5_18_11_2014.Models.Comment

@using (Html.BeginForm("Create", "Comment", FormMethod.Post,new{id="my-form" }))
{
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Add Comment</legend>

        <div class="editor-field">
            @Html.TextAreaFor(model => model.Body)
            @Html.ValidationMessageFor(model => model.Body)
        </div>
        @Html.Hidden("idpost",ViewData["idpost"])


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}
<script src="~/Scripts/addComment.js"></script>